name: CI Pipeline for ASP.NET API Application using Dockerhub

on:
  push:
    branches: ["web-012-backend-api"]
    tags:
      - "v*.*"
  pull_request:
    branches: ["web-012-backend-api"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        id: vars
        run: |
          tag=${GITHUB_REF#refs/*/}
          tag=${tag%% *}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Setup Git Config
        run: |
          git config user.name "Stephen Phyo"
          git config user.email "stephenphyo2019.official@gmail.com"

      - name: Save Version
        id: version
        run: echo ::set-output name=tag

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Build & Push to Docker Hub Repository
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile.prod
          tags: |
            ${{  secrets.DOCKER_USERNAME }}/web-012-employee-management-system-backend:${{ steps.vars.outputs.tag }}
            ${{  secrets.DOCKER_USERNAME }}/web-012-employee-management-system-backend:latest
